project:
  type: website
  output-dir: docs

website:
  title: "Andrew Isaak"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: index_de.qmd
        text: Deutsch

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
